import { objectType } from "@material-tailwind/react/types/components/checkbox";

export async function getProductDetails(slug:any) {

  const data:objectType = {
    "vespa-conversion": {id:1, name:"Vespa Conversion Kit", category: "eMotorcycle", description:"Are you ready to experience cycling like never before? Say hello to Vector Phantom H1, the ultimate fusion of technology and the age-old joy of riding. Conquer challenging terrains effortlessly with its high-performance motor and enjoy a safe journey with smart features. Embrace the joy of commuting and exploring while leaving a minimal carbon footprint. Elevate your cycling with our state of the art Vector Phantom H1, stylish, convenient, and sustainable. Effortlessly ride through traffic with the powerful motor, stay safe with advanced features, and explore more with an extended battery range. Join the electric biking revolution and create cherished memories with loved ones while contributing to a greener planet.", image_path:'/images/products/eATV/eATV_outdoor.JPG'},
    "raptor-e3": {id:6, name:"RAPTOR E3", category: "eMotorcycle", description:"Are you ready to experience cycling like never before? Say hello to Vector Phantom H1, the ultimate fusion of technology and the age-old joy of riding. Conquer challenging terrains effortlessly with its high-performance motor and enjoy a safe journey with smart features. Embrace the joy of commuting and exploring while leaving a minimal carbon footprint. Elevate your cycling with our state of the art Vector Phantom H1, stylish, convenient, and sustainable. Effortlessly ride through traffic with the powerful motor, stay safe with advanced features, and explore more with an extended battery range. Join the electric biking revolution and create cherished memories with loved ones while contributing to a greener planet.", image_path:'/images/products/eATV/eATV_outdoor.JPG'},
    "takara": {id:10, name:"TAKARA", category: "eMotorcycle", description:"Are you ready to experience cycling like never before? Say hello to Vector Phantom H1, the ultimate fusion of technology and the age-old joy of riding. Conquer challenging terrains effortlessly with its high-performance motor and enjoy a safe journey with smart features. Embrace the joy of commuting and exploring while leaving a minimal carbon footprint. Elevate your cycling with our state of the art Vector Phantom H1, stylish, convenient, and sustainable. Effortlessly ride through traffic with the powerful motor, stay safe with advanced features, and explore more with an extended battery range. Join the electric biking revolution and create cherished memories with loved ones while contributing to a greener planet.", image_path:'/images/products/eATV/eATV_outdoor.JPG'},
    "trion-m35": {id:2, name:"TRION M35", category: "eScooter", description:"Are you ready to experience cycling like never before? Say hello to Vector Phantom H1, the ultimate fusion of technology and the age-old joy of riding. Conquer challenging terrains effortlessly with its high-performance motor and enjoy a safe journey with smart features. Embrace the joy of commuting and exploring while leaving a minimal carbon footprint. Elevate your cycling with our state of the art Vector Phantom H1, stylish, convenient, and sustainable. Effortlessly ride through traffic with the powerful motor, stay safe with advanced features, and explore more with an extended battery range. Join the electric biking revolution and create cherished memories with loved ones while contributing to a greener planet.", image_path:'/images/products/eATV/eATV_outdoor.JPG'},
    "phantom-v1": {id:3, name:"PHANTOM V1", category: "eBike", description:"Are you ready to experience cycling like never before? Say hello to Vector Phantom H1, the ultimate fusion of technology and the age-old joy of riding. Conquer challenging terrains effortlessly with its high-performance motor and enjoy a safe journey with smart features. Embrace the joy of commuting and exploring while leaving a minimal carbon footprint. Elevate your cycling with our state of the art Vector Phantom H1, stylish, convenient, and sustainable. Effortlessly ride through traffic with the powerful motor, stay safe with advanced features, and explore more with an extended battery range. Join the electric biking revolution and create cherished memories with loved ones while contributing to a greener planet.", image_path:'/images/products/eATV/eATV_outdoor.JPG'},
    "alpha-r1": {id:4, name:"ALPHA R1", category: "eMotorcycle", description:"Are you ready to experience cycling like never before? Say hello to Vector Phantom H1, the ultimate fusion of technology and the age-old joy of riding. Conquer challenging terrains effortlessly with its high-performance motor and enjoy a safe journey with smart features. Embrace the joy of commuting and exploring while leaving a minimal carbon footprint. Elevate your cycling with our state of the art Vector Phantom H1, stylish, convenient, and sustainable. Effortlessly ride through traffic with the powerful motor, stay safe with advanced features, and explore more with an extended battery range. Join the electric biking revolution and create cherished memories with loved ones while contributing to a greener planet.", image_path:'/images/products/eATV/eATV_outdoor.JPG'},
    "iconic-z5": {id:5, name:"ICONIC Z5", category: "eATV", description:"Are you ready to experience cycling like never before? Say hello to Vector Phantom H1, the ultimate fusion of technology and the age-old joy of riding. Conquer challenging terrains effortlessly with its high-performance motor and enjoy a safe journey with smart features. Embrace the joy of commuting and exploring while leaving a minimal carbon footprint. Elevate your cycling with our state of the art Vector Phantom H1, stylish, convenient, and sustainable. Effortlessly ride through traffic with the powerful motor, stay safe with advanced features, and explore more with an extended battery range. Join the electric biking revolution and create cherished memories with loved ones while contributing to a greener planet.", image_path:'/images/products/eATV/eATV_outdoor.JPG'},
    "trion-d5": {id:7, name:"TRION D5", category: "eScooter", description:"Are you ready to experience cycling like never before? Say hello to Vector Phantom H1, the ultimate fusion of technology and the age-old joy of riding. Conquer challenging terrains effortlessly with its high-performance motor and enjoy a safe journey with smart features. Embrace the joy of commuting and exploring while leaving a minimal carbon footprint. Elevate your cycling with our state of the art Vector Phantom H1, stylish, convenient, and sustainable. Effortlessly ride through traffic with the powerful motor, stay safe with advanced features, and explore more with an extended battery range. Join the electric biking revolution and create cherished memories with loved ones while contributing to a greener planet.", image_path:'/images/products/eATV/eATV_outdoor.JPG'},
    "phantom-h5": {id:8, name:"PHANTOM H5", category: "eBike", description:"Are you ready to experience cycling like never before? Say hello to Vector Phantom H1, the ultimate fusion of technology and the age-old joy of riding. Conquer challenging terrains effortlessly with its high-performance motor and enjoy a safe journey with smart features. Embrace the joy of commuting and exploring while leaving a minimal carbon footprint. Elevate your cycling with our state of the art Vector Phantom H1, stylish, convenient, and sustainable. Effortlessly ride through traffic with the powerful motor, stay safe with advanced features, and explore more with an extended battery range. Join the electric biking revolution and create cherished memories with loved ones while contributing to a greener planet.", image_path:'/images/products/eATV/eATV_outdoor.JPG'},
    "nemesis-a5": {id:9, name:"NEMESIS A5", category: "Electric Smart Balance", description:"Are you ready to experience cycling like never before? Say hello to Vector Phantom H1, the ultimate fusion of technology and the age-old joy of riding. Conquer challenging terrains effortlessly with its high-performance motor and enjoy a safe journey with smart features. Embrace the joy of commuting and exploring while leaving a minimal carbon footprint. Elevate your cycling with our state of the art Vector Phantom H1, stylish, convenient, and sustainable. Effortlessly ride through traffic with the powerful motor, stay safe with advanced features, and explore more with an extended battery range. Join the electric biking revolution and create cherished memories with loved ones while contributing to a greener planet.", image_path:'/images/products/eATV/eATV_outdoor.JPG'},
  }

  return data[slug];
}


export async function getAllProducts() {
  const datas:any = [
    {id:1, slug: "vespa-conversion", name:"Vespa Conversion Kit", category: "eMotorcycle", description:"Lorem ipsum dolor amet", image_path:'/images/products/eATV/eATV_outdoor.JPG'},
    {id:6, slug: "raptor-e3", name:"RAPTOR E3", category: "eMotorcycle", description:"Lorem ipsum dolor amet", image_path:'/images/products/eATV/eATV_outdoor.JPG'},
    {id:10, slug: "takara", name:"TAKARA", category: "eMotorcycle", description:"Lorem ipsum dolor amet", image_path:'/images/products/eATV/eATV_outdoor.JPG'},
    {id:2, slug: "trion-m35", name:"TRION M35", category: "eScooter", description:"Electric Scooter", image_path:'/images/products/eATV/eATV_outdoor.JPG'},
    {id:3, slug: "phantom-v1", name:"PHANTOM V1", category: "eBike", description:"", image_path:'/images/products/eATV/eATV_outdoor.JPG'},
    {id:4, slug: "alpha-r1", name:"ALPHA R1", category: "eMotorcycle", description:"Lorem ipsum dolor amet", image_path:'/images/products/eATV/eATV_outdoor.JPG'},
    {id:5, slug: "iconic-z5", name:"ICONIC Z5", category: "eATV", description:"Lorem ipsum dolor amet", image_path:'/images/products/eATV/eATV_outdoor.JPG'},
    {id:7, slug: "trion-d5", name:"TRION D5", category: "eScooter", description:"First ever vector product", image_path:'/images/products/eATV/eATV_outdoor.JPG'},
    {id:8, slug: "phantom-h5", name:"PHANTOM H5", category: "eBike", description:"Lorem ipsum dolor amet", image_path:'/images/products/eATV/eATV_outdoor.JPG'},
    {id:9, slug: "nemesis-a5", name:"NEMESIS A5", category: "Electric Smart Balance", description:"Lorem ipsum dolor amet", image_path:'/images/products/eATV/eATV_outdoor.JPG'},
  ]

  return datas;
}